language: 
    python
python:
    - "2.7"
    - "3.5"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script: nosetests --with-coverage --cover-package=scirate
notifications:
    email: false
after_success:
    coveralls
